### ISSUE TITLE
Memory leak when unmounted before promise finished

### ISSUE THREAD

**Issue by hoschi** [aiven715/promise-hook#1]
I was curious about `useState` and `useEffect` works and saw you project. There is still that problem that a promise can't be cancelled. You can check the problem here: https://codesandbox.io/s/zq0w38lyy4

When you guard the `setXX` calls which change your state, you can prevent that error by adding cleanup logic in `useEffect`. See the changes in `ph.js`: https://codesandbox.io/s/ox9mmzo105

By the way: Please add a licence to this repository :wink:

**Comment by saivanji** [comment]
Hey @hoschi great observation!

I've fixed that issue in 0.1.4
