### ISSUE TITLE
React Hooks must be called in the exact same order in every component render

### ISSUE THREAD

**Issue by alexesDev** [aiven715/promise-hook#2]
eslint-plugin-react-hooks found en error:

> React Hook "useEffect" is called conditionally. React Hooks must be called in the exact same order in every component render. (react-hooks/rules-of-hooks)

![screen](https://user-images.githubusercontent.com/1255344/50755808-34e90d80-126b-11e9-9d16-5d6f2010468d.png)

https://reactjs.org/docs/hooks-rules.html

> Don’t call Hooks inside loops, conditions, or nested functions.

**Comment by abumalick** [comment]
changing it to 
```
useEffect(() => {
  if (resolve) {
    request()
  }
}, resolveCondition)
```
should fix the problem @aiven715

**Comment by saivanji** [comment]
@abumalick thanks, will check
